# Generated by Django 4.1 on 2022-09-07 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endnum',
            old_name='flop',
            new_name='x1',
        ),
        migrations.RemoveField(
            model_name='endnum',
            name='net',
        ),
        migrations.RemoveField(
            model_name='endnum',
            name='net2',
        ),
        migrations.RemoveField(
            model_name='endnum',
            name='net3',
        ),
        migrations.AddField(
            model_name='endnum',
            name='x2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='endnum',
            name='x3',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
